# -*- coding: utf-8 -*-

# https://projecteuler.net/problem=29
# Distinct powers

# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

from timeit import default_timer as timer

t_start = timer()

a = range(2, 100+1)
b = range(2, 100+1)

pairs = []

for i in a:
    pairs.extend(zip([i] * len(b), b))

rv = set()

for p in pairs:
    rv.add(p[0]**p[1])

rv = len(rv)
print rv, timer() - t_start